# Generated by Django 2.1.5 on 2020-06-15 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='info',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contact', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=250)),
            ],
        ),
    ]
